### ISSUE TITLE
Shownav="false" not working.

### ISSUE THREAD

**Issue by dasalvar** [arjunjain/wpnewcarousels#1]
Hi, 

I want to remove the nav from the slider but the label shownav="false" is not working.

This is the code I wrote:

[wpnewcarousel name="PatrocinadoresIzq" width="300" height="100" effect="fade" startslide=" " animationspeed=" " imagepausetime=" " shownav="false" hoverpause="true" ]

Using WPNewCarousels Version 1.6

**Comment by arjunjain** [comment]
please update to latest version
